[window]
dynamic_padding = true
# opacity = 0.97
# padding = { x = 0, y = 0 }

[env]
TERM = "xterm-256color"

[font]
size = 14
# offset = { y = 2 }
# glyph_offset = { y = 1 }

# normal = { family = "Berkeley Mono", style = "Medium" }
# bold = { family = "Berkeley Mono", style = "Bold" }
# bold_italic = { family = "Berkeley Mono", style = "Bold Italic" }
# italic = { family = "Berkeley Mono", style = "Italic" }

# normal = { family = "Iosevka Nerd Font", style = "Medium" }
# bold = { family = "Iosevka Nerd Font", style = "Bold" }
# italic = { family = "Iosevka Nerd Font", style = "Medium Italic" }
# bold_italic = { family = "Iosevka Nerd Font", style = "Bold Italic" }

# [ colors.primary ]
# background = '#131313'
